### ISSUE TITLE
PERCENT_DUPLICATION is a fraction

### ISSUE THREAD

**Issue by plijnzaad** [broadinstitute/picard#344]
Issue https://github.com/broadinstitute/picard/issues/157 says this issue will not be resolved, but could the documentation please be adjusted? The [FAQ describes it correctly](http://broadinstitute.github.io/picard/faq.html), but    https://broadinstitute.github.io/picard/picard-metric-definitions.html still says:

```
PERCENT_DUPLICATION	    The percentage of mapped sequence that is marked as duplicate.
```
(incidentally, it looks like all `PCT_` values are really fractions rather than percentages, it mightn't hurt to state this more clearly)

**Comment by vdauwera** [comment]
Well shoot we just did a big push to clean up the docs -- will address this in the next round.

**Comment by yfarjoun** [comment]
This is true. all PCT in picard are fractions.

**Comment by dekling** [comment]
This was addressed by @sooheelee in a blog post (https://www.broadinstitute.org/gatk/blog?id=7264).

**Comment by vdauwera** [comment]
Actually we should also fix the docs in the metrics classes. Our blog post was an attempt to raise awareness to this problem, but it can't be considered a substitute for fixing the docs.

**Comment by dekling** [comment]
Issue moved to [broadinstitute/dsde-docs #903](https://github.com/broadinstitute/dsde-docs/issues/903) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by dekling** [comment]
Tried to move this to DSDE-Docs.  Not sure if it worked.

**Comment by plijnzaad** [comment]
The https://github.com/broadinstitute/dsde-docs/issues/903 link is broken (and I am puzzled why this issue has been closed again, the docs are not fixed as far as I can see. Mentioning something in a blog is far from 'addressing' it, IMHO ...)

**Comment by dekling** [comment]
Hi @plijnzaad:  I can assure you that it is being worked on as I write this.  The ticket has simply been moved to a different repo where it has greater visibility.  Thanks for your vigilance on this!

**Comment by plijnzaad** [comment]
OK, sorry, thank!

**Comment by yfarjoun** [comment]
This can be closed...right?

**Comment by vdauwera** [comment]
Yes it's done.
